# Generated by Django 3.2.5 on 2022-04-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TarotCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('tag', models.CharField(max_length=30)),
                ('src', models.URLField()),
                ('group', models.CharField(max_length=15)),
                ('text', models.TextField()),
            ],
        ),
    ]
